//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooStore.Properties
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Drawing;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("Manual", "1.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resources()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("ZooStore.Properties.Resources", typeof(Resources).Assembly);
                }

                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static Bitmap acana_pacifica => (Bitmap)ResourceManager.GetObject("acana_pacifica", resourceCulture);
        internal static Bitmap beaphar_chamomile => (Bitmap)ResourceManager.GetObject("beaphar_chamomile", resourceCulture);
        internal static Bitmap beaphar_collar => (Bitmap)ResourceManager.GetObject("beaphar_collar", resourceCulture);
        internal static Bitmap beaphar_ferret => (Bitmap)ResourceManager.GetObject("beaphar_ferret", resourceCulture);
        internal static Bitmap bell_toy => (Bitmap)ResourceManager.GetObject("bell_toy", resourceCulture);
        internal static Bitmap catsbest_5l => (Bitmap)ResourceManager.GetObject("catsbest_5l", resourceCulture);
        internal static Bitmap cat_grass => (Bitmap)ResourceManager.GetObject("cat_grass", resourceCulture);
        internal static Bitmap dentastix => (Bitmap)ResourceManager.GetObject("dentastix", resourceCulture);
        internal static Bitmap ferplast_2floor => (Bitmap)ResourceManager.GetObject("ferplast_2floor", resourceCulture);
        internal static Bitmap ferplast_bowl => (Bitmap)ResourceManager.GetObject("ferplast_bowl", resourceCulture);
        internal static Bitmap flexi_tape => (Bitmap)ResourceManager.GetObject("flexi_tape", resourceCulture);
        internal static Bitmap gimcat_treats => (Bitmap)ResourceManager.GetObject("gimcat_treats", resourceCulture);
        internal static Bitmap hills_id_lowfat => (Bitmap)ResourceManager.GetObject("hills_id_lowfat", resourceCulture);
        internal static Bitmap hunter_leash => (Bitmap)ResourceManager.GetObject("hunter_leash", resourceCulture);
        internal static Bitmap ivsb_spray => (Bitmap)ResourceManager.GetObject("ivsb_spray", resourceCulture);
        internal static Bitmap kogtetochka_50 => (Bitmap)ResourceManager.GetObject("kogtetochka_50", resourceCulture);
        internal static Bitmap Logotip => (Bitmap)ResourceManager.GetObject("Logotip", resourceCulture);
        internal static Bitmap mouse_catnip => (Bitmap)ResourceManager.GetObject("mouse_catnip", resourceCulture);
        internal static Bitmap orijen_original => (Bitmap)ResourceManager.GetObject("orijen_original", resourceCulture);
        internal static Bitmap picture => (Bitmap)ResourceManager.GetObject("picture", resourceCulture);
        internal static Bitmap prestige_parrot => (Bitmap)ResourceManager.GetObject("prestige_parrot", resourceCulture);
        internal static Bitmap proplan_puppy => (Bitmap)ResourceManager.GetObject("proplan_puppy", resourceCulture);
        internal static Bitmap rc_sterilised => (Bitmap)ResourceManager.GetObject("rc_sterilised", resourceCulture);
        internal static Bitmap savic_carrier => (Bitmap)ResourceManager.GetObject("savic_carrier", resourceCulture);
        internal static Bitmap smarttail_mat => (Bitmap)ResourceManager.GetObject("smarttail_mat", resourceCulture);
        internal static Bitmap tetra_min => (Bitmap)ResourceManager.GetObject("tetra_min", resourceCulture);
        internal static Bitmap tetra_reptomin => (Bitmap)ResourceManager.GetObject("tetra_reptomin", resourceCulture);
        internal static Bitmap trixie_bed => (Bitmap)ResourceManager.GetObject("trixie_bed", resourceCulture);
        internal static Bitmap trixie_postop => (Bitmap)ResourceManager.GetObject("trixie_postop", resourceCulture);
        internal static Bitmap trixie_slicker => (Bitmap)ResourceManager.GetObject("trixie_slicker", resourceCulture);
        internal static Bitmap versele_laga_hamster => (Bitmap)ResourceManager.GetObject("versele_laga_hamster", resourceCulture);
        internal static Bitmap zeolit_38l => (Bitmap)ResourceManager.GetObject("zeolit_38l", resourceCulture);
        internal static Icon Иконка => (Icon)ResourceManager.GetObject("Иконка", resourceCulture);
    }
}
